/** @type {{ NOT_SUBMITTED: 'NOT_SUBMITTED'; UNDER_REVIEW: 'UNDER_REVIEW'; UPDATE_REQUESTED: 'UPDATE_REQUESTED'; APPROVED: 'APPROVED'; REJECTED: 'REJECTED' }} */
export const REQUEST_STATE = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  UPDATE_REQUESTED: 'UPDATE_REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

/** @type {{ SUBMIT: 'SUBMIT'; REQUEST_UPDATE: 'REQUEST_UPDATE'; APPROVE: 'APPROVE'; REJECT: 'REJECT' }} */
export const USER_ACTION_TYPE = {
  SUBMIT: 'SUBMIT',
  REQUEST_UPDATE: 'REQUEST_UPDATE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
};
